export EDITOR="nvim"
export PATH="$HOME/.local/bin:$PATH"

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH

# Path to your Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time Oh My Zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="robbyrussell"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  git 
  zsh-syntax-highlighting 
  zsh-autosuggestions
)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='nvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch $(uname -m)"

# Set personal aliases, overriding those provided by Oh My Zsh libs,
# plugins, and themes. Aliases can be placed here, though Oh My Zsh
# users are encouraged to define aliases within a top-level file in
# the $ZSH_CUSTOM folder, with .zsh extension. Examples:
# - $ZSH_CUSTOM/aliases.zsh
# - $ZSH_CUSTOM/macos.zsh
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
source ~/powerlevel10k/powerlevel10k.zsh-theme

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# 이 코드 세그먼트를 .zshrc 파일에 복사
# nvm 초기화 후에 배치하세요!
autoload -U add-zsh-hook
load-nvmrc() {
  local nvmrc_path="$(nvm_find_nvmrc)"

  if [ -n "$nvmrc_path" ]; then
    local nvmrc_node_version=$(nvm version "$(cat "${nvmrc_path}")")

    if [ "$nvmrc_node_version" = "N/A" ]; then
      nvm install
    elif [ "$nvmrc_node_version" != "$(nvm version)" ]; then
      nvm use
    fi
  elif [ -n "$(PWD=$OLDPWD nvm_find_nvmrc)" ] && [ "$(nvm version)" != "$(nvm version default)" ]; then
    echo "Reverting to nvm default version"
    nvm use default
  fi
}
add-zsh-hook chpwd load-nvmrc
load-nvmrc

# pyenv
export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init - zsh)"

# Set up fzf key bindings and fuzzy completion
source <(fzf --zsh)
# alt + c for XOS config
bindkey ç fzf-cd-widget
# open file with cursor
alias f='cursor $(fzf)'

# 검색 후 파일 열기
rgo() {
  local query="$1"
  if [ -z "$query" ]; then
    rg --files
  else
    rg -l "$query"
  fi | fzf -m --preview "bat --style=numbers --color=always {}" | xargs -r cursor
}

# git log
alias gl='git log --oneline --graph --decorate --all'
# open git diff file with cursor
alias gdiff='git status -s | awk "{print \$2}" | fzf -m | xargs -r cursor'

# search for TODO or FIXME in files and open with cursor
alias todo='rg -n "TODO|FIXME" | fzf -m --delimiter : --preview "bat --style=numbers --color=always {1} --highlight-line {2}" | awk -F: "{print \$1 \":\" \$2}" | xargs -r cursor --goto'

# python
alias py='python'
alias venv='python -m venv .venv'
alias activate='source .venv/bin/activate'
alias freeze='pip freeze > requirements.txt'
alias pir='pip install -r requirements.txt'
alias pi='pip install'

# zoxide, fd, tree
# zoxide
eval "$(zoxide init zsh)"
# auto cd
setopt AUTO_CD
# cdf with preview
cdf() {
  local dir
  dir=$(fd -t d --hidden --exclude .git | \
    fzf --preview 'tree -C {} | head -200') || return
  cd "$dir"
}
# previous dir
alias bd='cd -'

# eza
# ls - 기본 파일보기
alias ls='eza'
# ld - 디렉터리만 나열합니다(파일 없음)
alias ld='eza -lD'
# lf - 파일만 나열합니다(디렉터리 없음)
alias lf='eza -lF --color=always | grep -v /'
# lh - 숨겨진 파일만 나열합니다(디렉토리 없음)
alias lh='eza -dl .* --group-directories-first'
# lll - 디렉토리가 있는 모든 것을 먼저 나열합니다
alias lll='eza -al --group-directories-first'
# lls - 크기별로 정렬된 파일만 나열합니다
alias lls='eza -alF --color=always --sort=size | grep -v /'
# lt - 업데이트된 시간순으로 모든 파일을 나열합니다
alias lt='eza -al --sort=modified'

# nvim
alias vi='nvim'
alias vim='nvim'

# 자주 사용하는 명령어
alias top='htop'
alias cat='bat'
alias find='fd'
alias grep='rg'

# 개발 관련
alias myip='curl ifconfig.me'
alias ports='lsof -i -P -n | grep LISTEN'
alias reload='source ~/.zshrc'

# 시스템 관리
alias cleanup='brew cleanup && brew autoremove'
alias update='brew update && brew upgrade'
alias clean='find . -type f -name "*.DS_Store" -delete'


# tmux
alias ta='tmux attach-session -t'
alias ts='tmux new-session -s'
alias tl='tmux list-sessions'
alias tk='tmux kill-session -t'
alias tmuxr="tmux source-file ~/.tmux.conf"
alias mux="tmuxinator"
